name: 3D Action

on:
  schedule:
    - cron: '0 5 * * 2,4,6'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: GitHub-Profile-3D-Contrib
    
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0

        env:   
          GITHUB_TOKEN: ${{ secrets.GIT_STATUS }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "GitHub Actions: Updated"
          git push
